name: Build and Deploy to Harbor

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login https://registry.hextech.online/ -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build --tag https://registry.hextech.online/k8s/demo-server:${{ github.run_id }} .

      - name: Push Docker image
        run: |
          docker push https://registry.hextech.online/k8s/demo-server:${{ github.run_id }}

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: https://registry.hextech.online/k8s/demo-server:.*|image: https://registry.hextech.online/k8s/demo-server:${{ github.run_id }}|" k8s-manifests/deployment.yaml

      - name: Commit and push manifest
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s-manifests/deployment.yaml
          git commit -m "Update image tag to ${{ github.run_id }}"
          git push