apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-flux
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s-manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: demo-flux
  validation: client