apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: demo-flux
  namespace: flux-system
interval: 10m0s
path: ./k8s-manifests
prune: true
sourceRef:
  kind: GitRepository
  name: demo-flux
validation: client